DROP TABLE IF EXISTS VIVEROS ;

CREATE TABLE IF NOT EXISTS VIVEROS (
  ID_Viveros VARCHAR(12) NOT NULL,
  LAT DECIMAL NULL,
  LON DECIMAL NULL,
  Tam_Vivero VARCHAR(9) NULL,
  PRIMARY KEY (ID_Viveros));



DROP TABLE IF EXISTS ZONAS ;

CREATE TABLE IF NOT EXISTS ZONAS (
  ID_Zona VARCHAR(12) NOT NULL,
  Tipo_Zona VARCHAR(10) NOT NULL,
  Tam_Zona VARCHAR(9) NULL,
  Stock_Prod INT NULL,
  VIVEROS_ID_Viveros VARCHAR(12) NOT NULL,
  PRIMARY KEY (ID_Zona),
    FOREIGN KEY (VIVEROS_ID_Viveros)
    REFERENCES VIVEROS (ID_Viveros)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP TABLE IF EXISTS PRODUCTOS ;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
  ID_Prod VARCHAR(12) NOT NULL,
  Stock INT NOT NULL,
  Nombre_Prod VARCHAR(45) NOT NULL,
  ZONAS_ID_Zona VARCHAR(12) NOT NULL,
  PRIMARY KEY (ID_Prod),
    FOREIGN KEY (ZONAS_ID_Zona)
    REFERENCES ZONAS (ID_Zona)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



DROP TABLE IF EXISTS CLIENTES ;

CREATE TABLE IF NOT EXISTS CLIENTES (
  ID_Cliente INT NOT NULL,
  Direccion VARCHAR(45) NULL,
  PRIMARY KEY (ID_Cliente));



DROP TABLE IF EXISTS EMPLEADOS ;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
  ID_Empleado INT NOT NULL,
  ZONAS_ID_Zona VARCHAR(12) NOT NULL,
  PRIMARY KEY (ID_Empleado),
  CONSTRAINT fk_EMPLEADOS_ZONAS1
    FOREIGN KEY (ZONAS_ID_Zona)
    REFERENCES ZONAS (ID_Zona)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP TABLE IF EXISTS VENTAS ;

CREATE TABLE IF NOT EXISTS VENTAS (
  EMPLEADOS_ID_Empleado INT NOT NULL,
  CLIENTES_ID_Cliente INT NOT NULL,
  PRODUCTOS_ID_Prod VARCHAR(12) NOT NULL,
  Fecha DATE NULL,
  Cantidad VARCHAR(45) NULL,
    FOREIGN KEY (EMPLEADOS_ID_Empleado)
    REFERENCES EMPLEADOS (ID_Empleado)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (CLIENTES_ID_Cliente)
    REFERENCES CLIENTES (ID_Cliente)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (PRODUCTOS_ID_Prod)
    REFERENCES PRODUCTOS (ID_Prod)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


INSERT INTO VIVEROS (ID_Viveros, LAT, LON, Tam_Vivero) VALUES ('111111', 16.7687, -4.67896, '20x50');
INSERT INTO VIVEROS (ID_Viveros, LAT, LON, Tam_Vivero) VALUES ('111111', 16.7687, -4.67896, '20x50');

INSERT INTO ZONAS (ID_Zona, Tipo_Zona, Tam_Zona, Stock_Prod, VIVEROS_ID_Viveros) VALUES ('Z11111', 'Almacen', '10x20', NULL, '111111');
INSERT INTO ZONAS (ID_Zona, Tipo_Zona, Tam_Zona, Stock_Prod, VIVEROS_ID_Viveros) VALUES ('Z22222', 'Exterior', '10x3', NULL, '111111');